version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    command: npx nodos server -h 0.0.0.0
    volumes:
      - .:/app

  caddy:
    image: caddy:2.4.1-alpine
    container_name: hexlet_devops_server
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app
