version: "3.9"

services:
  db:
    image: postgres:13.3
    container_name: hexlet_devops_db
    environment:
      POSTGRES_PASSWORD: ${NODOS_DB_PASSWORD:-postgres}
      POSTGRES_USER: ${NODOS_DB_USERNAME:-postgres}

  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: hexlet_devops_app
    image: hexlet_devops_app_image
    command: npm test
    depends_on:
      - db
