version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${NODOS_DB_PASSWORD:-postgres}
      POSTGRES_USER: ${NODOS_DB_USERNAME:-postgres}

  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: npm test
    volumes:
      - .:/app
    depends_on:
      - db
