version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${NODOS_DB_PASSWORD}
      POSTGRES_USER: ${NODOS_DB_USERNAME}

  app:
    build: .
    command: npm test
    volumes:
      - .:/app
    depends_on:
      - db
